"""
Django settings for lumieres_project project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# TODO: logging DEBUG: BASE_DIR

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-4*k!-kghhr5h!=hhmi#sbt-8mnv%@2ks%g_u7e_uq_v5e)0-v9"
# FIXME: make a production SECRET_KEY system

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# TODO: switch the source variable to a var env.

ALLOWED_HOSTS = []  # TODO: limits the hosts that can access the application.

# TODO: X-Frame-Options SAMEORIGINE ???

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # XXX: "django.contrib.sites",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",  # XXX: sea about SAMEORIGNE L32
]

ROOT_URLCONF = "lumieres_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],  # TODO: create the template folders
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                # XXX: "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "lumieres_project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.getenv("MYSQL_DATABASE", "lumieres_lausanne"),  # Use environment variable or default to 'django_db'
        "USER": os.getenv("MYSQL_USER", "lluser-dev"),  # Use environment variable or default to 'django_user'
        "PASSWORD": os.getenv(
            "MYSQL_PASSWORD", "lluser-password"
        ),  # Use environment variable or default to 'django_password'
        "HOST": os.getenv("MYSQL_HOST", "db"),  # Ensure this matches your Docker service name
        "PORT": os.getenv("MYSQL_PORT", "3306"),  # Use environment variable or default to '3306'
        "OPTIONS": {
            "charset": "utf8mb4",  # Ensure proper character encoding
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-ch"

TIME_ZONE = "Europe/Zurich"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
# TODO: STATIC_ROOT and STATIC_FOLDERS ?


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Media files (Uploaded content)
# https://docs.djangoproject.com/en/5.1/topics/files/

# XXX: check that
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "tmp" / "media"
