"""
Django settings for lumieres project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
from datetime import datetime

BASE_DIR = Path(__file__).resolve().parent  # /app/lumieres/lumieres_project

# ------------------------------
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/
# ------------------------------

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-#+_qt^k0$c5sw@ry!r$*^dyw6$zvf(s8jb6_6jtcryb=cnmozb"

# X-Frame-Options
X_FRAME_OPTIONS = "SAMEORIGIN"

# ---------------------------------
# Environment & host/origin settings
# ---------------------------------

# 'development' | 'staging' | 'production'
ENV = os.getenv("DJANGO_ENV", "development").lower()

# DEBUG:
# - default True in development, False otherwise (can be overridden via DJANGO_DEBUG)
DEBUG_DEFAULT = "1" if ENV == "development" else "0"
DEBUG = os.getenv("DJANGO_DEBUG", DEBUG_DEFAULT).lower() in ("1", "true", "yes")

# Allowed hosts & CSRF trusted origins per environment
if ENV == "production":
    ALLOWED_HOSTS = ["lumieres.unil.ch"]
    CSRF_TRUSTED_ORIGINS = ["https://lumieres.unil.ch"]
elif ENV == "staging":
    ALLOWED_HOSTS = ["plt-tst-2.unil.ch"]
    CSRF_TRUSTED_ORIGINS = ["https://plt-tst-2.unil.ch"]
else:  # development
    ALLOWED_HOSTS = ["localhost", "127.0.0.1", "[::1]", "0.0.0.0"]
    CSRF_TRUSTED_ORIGINS = []

# Reverse proxy/TLS termination (Apache on staging/prod)
# Ensure Apache sets: RequestHeader set X-Forwarded-Proto "https"
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Enforce HTTPS & secure cookies outside dev
SECURE_SSL_REDIRECT = ENV != "development"
SESSION_COOKIE_SECURE = ENV != "development"
CSRF_COOKIE_SECURE = ENV != "development"

# ------------------------------
# Application definition
# ------------------------------

INSTALLED_APPS = [
    # Django default apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",

    # Third-party apps
    "haystack",
    "ckeditor",
    "ckeditor_uploader",
    "sorl.thumbnail",

    # Custom apps
    "fiches",
    "pagination",
]

SITE_ID = 1

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "lumieres_project.urls"
WSGI_APPLICATION = "lumieres_project.wsgi.application"
ASGI_APPLICATION = "lumieres_project.asgi.application"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",  # This corresponds to /app/lumieres/templates/
            BASE_DIR / "fiches" / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# ------------------------------
# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
# ------------------------------

import os

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.getenv("MYSQL_DATABASE", "lumieres_lausanne"),  # Use environment variable or default to 'django_db'
        "USER": os.getenv("MYSQL_USER", "lluser-dev"),  # Use environment variable or default to 'django_user'
        "PASSWORD": os.getenv(
            "MYSQL_PASSWORD", "lluser-password"
        ),  # Use environment variable or default to 'django_password'
        "HOST": "db",  # Ensure this matches your Docker service name
        "PORT": "3306",
        "OPTIONS": {
            "charset": "utf8mb4",  # Ensure proper character encoding
        },
    }
}

# ------------------------------
# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators
# ------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# ------------------------------
# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/
# ------------------------------

LANGUAGE_CODE = "fr-ch"

TIME_ZONE = "Europe/Zurich"

USE_I18N = True

USE_TZ = True

#DEFAULT_CHARSET = "utf-8"

# ------------------------------
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
# ------------------------------

STATIC_URL = "/static/"

# Directory where static files are collected via `collectstatic`:
STATIC_ROOT = BASE_DIR / "staticfiles"

# Additional directories to search for static files (in dev)
STATICFILES_DIRS = [
    BASE_DIR.parent / "static",  # /app/lumieres/static
    BASE_DIR.parent / "ckeditor/static",
]

# ------------------------------
# Media files (Uploaded content)
# ------------------------------

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR.parent / "media"

# ------------------------------
# CKEditor Configuration
# ------------------------------

CKEDITOR_UPLOAD_PATH = BASE_DIR.parent / "uploads"

from .settings_ckeditor_configs import CKEDITOR_CONFIGS

# ------------------------------
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field
# ------------------------------

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ------------------------------
# Additional Settings
# ------------------------------

# Security settings (adjust as needed for production)
# SECURE_SSL_REDIRECT = True
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True

# Health check endpoint can be added here if implemented

HAYSTACK_CONNECTIONS = {
    "default": {
        "ENGINE": "haystack.backends.solr_backend.SolrEngine",
        "URL": os.getenv("HAYSTACK_URL", "http://solr:8983/solr/lumieres"),
        "INCLUDE_SPELLING": True,
        "TIMEOUT": 5,
    },
}
HAYSTACK_SEARCH_RESULTS_PER_PAGE = 30
HAYSTACK_SIGNAL_PROCESSOR = "haystack.signals.RealtimeSignalProcessor"

# Redirect to homepage after login
LOGIN_REDIRECT_URL = "/"

# ------------------------------
# Caching Configuration
# ------------------------------

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "unique-snowflake",  # A unique name for the cache
    }
}

# -----------------------------
# Logging configurations
# -----------------------------

logfile = Path(BASE_DIR).parent.parent
logfile = logfile / "logging" / f"debug_{datetime.now().strftime('%Y-%m-%d_%H-%M-%S')}.log"
logfile.parent.mkdir(parents=True, exist_ok=True)  # Ensure the directory exists

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,

    "formatters": {
        "simple": {"format": "%(levelname)s %(name)s: %(message)s"},
    },

    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "level": "INFO",          # ↓ show info+ on console (no DEBUG spam)
            "formatter": "simple",
        },
        "file": {
            "class": "logging.FileHandler",
            "level": "DEBUG",         # keep full detail in file
            "filename": str(logfile),
        },
    },

    # Default/root logger
    "root": {
        "handlers": ["console", "file"],
        "level": "INFO",
    },

    "loggers": {
        # Silence the autoreload “first seen with mtime …” chatter
        "django.utils.autoreload": {
            "handlers": ["console", "file"],
            "level": "WARNING",
            "propagate": False,
        },
        # Mute SQL debug output like “(0.001) SELECT …”
        "django.db.backends": {
            "handlers": ["console", "file"],
            "level": "WARNING",
            "propagate": False,
        },
        # Optional: keep server request logs reasonable
        "django.server": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": False,
        },
        # Your app logger (adjust as you like)
        "lumieres_project": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": True,
        },
    },
}
