# Generated by Django 5.2 on 2026-05-27 11:58

import ckeditor.fields
import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import sorl.thumbnail.fields
import utils.fields
from django.conf import settings
from django.db import migrations, models

import fiches.models.documents.document


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JournaltitleView",
            fields=[
                (
                    "journal_title",
                    models.CharField(max_length=512, primary_key=True, serialize=False, verbose_name="Journal Title"),
                ),
            ],
            options={
                "verbose_name": "Journal Title View",
                "verbose_name_plural": "Journal Title Views",
                "db_table": "fiches_journaltitleview",
                "ordering": ["journal_title"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PlaceView",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("biblio_id", models.IntegerField(blank=True, null=True, verbose_name="Biblio ID")),
                ("place_name", models.CharField(max_length=255, verbose_name="Place Name")),
            ],
            options={
                "verbose_name": "Place View",
                "verbose_name_plural": "Place Views",
                "ordering": ["place_name"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SecondaryKeyword",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("word", models.CharField(max_length=100, unique=True, verbose_name="Mot")),
            ],
            options={
                "verbose_name": "Mot clé secondaire",
                "verbose_name_plural": "Mots clés secondaires",
                "db_table": "fiches_secondarykeyword",
                "ordering": ("primary_keyword__word", "word"),
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ContributionType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("code", models.IntegerField(unique=True, verbose_name="Code")),
                ("type", models.CharField(max_length=10, verbose_name="Type")),
            ],
        ),
        migrations.CreateModel(
            name="Depot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128, unique=True, verbose_name="Nom")),
            ],
            options={
                "verbose_name": "Lieu de dépôt",
                "verbose_name_plural": "Lieux de dépôt",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DocumentLanguage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=30)),
                ("code", models.CharField(blank=True, max_length=10)),
                ("ordering", models.IntegerField()),
            ],
            options={
                "verbose_name": "Langue de document",
                "verbose_name_plural": "Langues de document",
                "ordering": ["ordering", "name"],
            },
        ),
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=30)),
                ("code", models.IntegerField(default=-1)),
                (
                    "exclusive_fields",
                    models.CharField(
                        blank=True,
                        help_text="Liste des nom de champs du document qui n'apparaissent que pour ce type de document. Liste séparée par des virgules.",
                        max_length=512,
                    ),
                ),
            ],
            options={
                "verbose_name": "Type de document",
                "verbose_name_plural": "Types de document",
                "ordering": ["-code", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ManuscriptType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128)),
                ("sorting", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Type de manuscrit",
                "verbose_name_plural": "Types de manuscrit",
                "ordering": ["sorting"],
            },
        ),
        migrations.CreateModel(
            name="Nationality",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=512, verbose_name="Nationalité")),
            ],
            options={
                "verbose_name": "Nationalité",
                "verbose_name_plural": "Nationalités",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=215, verbose_name="Nom")),
                ("modern", models.BooleanField(blank=True, null=True, verbose_name="Personne littérature secondaire")),
                ("may_have_biography", models.BooleanField(default=True, verbose_name="Peut avoir une biographie")),
            ],
            options={
                "verbose_name": "Personne",
                "verbose_name_plural": "Personnes",
                "ordering": ["name"],
            },
            managers=[
                ("people", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="PrimaryKeyword",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("word", models.CharField(max_length=100, unique=True, verbose_name="Mot")),
            ],
            options={
                "verbose_name": "Mot clé principal",
                "verbose_name_plural": "Mots clés principaux",
                "ordering": ("word",),
            },
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
            ],
            options={
                "db_table": "fiches_publication",
            },
        ),
        migrations.CreateModel(
            name="RelationType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=256)),
                ("reverse_name", models.CharField(max_length=256)),
                ("sorting", models.IntegerField()),
            ],
            options={
                "verbose_name": "Type de relation",
                "verbose_name_plural": "Types de relation",
                "ordering": ["sorting"],
            },
        ),
        migrations.CreateModel(
            name="Religion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=256, verbose_name="Confession")),
                ("sorting", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["sorting"],
            },
        ),
        migrations.CreateModel(
            name="Society",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128, verbose_name="Société/Académie")),
            ],
            options={
                "verbose_name": "Société/Académie",
                "verbose_name_plural": "Sociétés/Académies",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.IntegerField()),
                ("model_name", models.CharField(max_length=256, verbose_name="Type d'objet")),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("p_orphan", models.BooleanField(blank=True, default=False, editable=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activité",
            },
        ),
        migrations.CreateModel(
            name="AttachedDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(blank=True, max_length=250, verbose_name="Titre")),
                ("file", models.FileField(upload_to="files/%Y/%m", verbose_name="Fichier")),
                ("object_id", models.PositiveIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Biblio",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.TextField(verbose_name="Titre")),
                ("short_title", models.CharField(blank=True, max_length=512, null=True, verbose_name="Titre court")),
                (
                    "litterature_type",
                    models.CharField(
                        choices=[("p", "Primaire"), ("s", "Secondaire")],
                        max_length=2,
                        verbose_name="Type de littérature",
                    ),
                ),
                ("book_title", models.CharField(blank=True, max_length=512, verbose_name="Titre du livre")),
                (
                    "collection",
                    models.CharField(blank=True, max_length=512, verbose_name="Collection et n° du volume"),
                ),
                ("journal_title", models.CharField(blank=True, max_length=512, verbose_name="Titre de la revue")),
                ("journal_num", models.CharField(blank=True, max_length=30, verbose_name="N° de la revue")),
                ("journal_abr", models.CharField(blank=True, max_length=60, verbose_name="Abréviation de la revue")),
                ("series_title", models.CharField(blank=True, max_length=512, verbose_name="Titre du numéro")),
                ("series_text", models.CharField(blank=True, max_length=512, verbose_name="Texte de la série")),
                (
                    "dictionary_title",
                    models.CharField(blank=True, max_length=256, verbose_name="Titre de dictionnaire"),
                ),
                ("inscription", models.CharField(blank=True, max_length=256, verbose_name="Dédicace")),
                ("place", models.CharField(blank=True, max_length=64, verbose_name="Lieu")),
                ("publisher", models.CharField(blank=True, max_length=256, verbose_name="Editeur")),
                ("place2", models.CharField(blank=True, max_length=64, verbose_name="2e Lieu")),
                ("publisher2", models.CharField(blank=True, max_length=256, verbose_name="2e Editeur")),
                ("edition", models.CharField(blank=True, max_length=128, verbose_name="Date de 1ère Edition")),
                ("date", models.DateField(blank=True, null=True, verbose_name="Date")),
                ("date_f", models.CharField(blank=True, max_length=15, null=True)),
                ("date2", models.DateField(blank=True, null=True, verbose_name="Date 2")),
                ("date2_f", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "volume",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(128),
                        ],
                        verbose_name="Volume",
                    ),
                ),
                ("volume_nb", models.IntegerField(blank=True, default=None, null=True, verbose_name="Nb de volumes")),
                ("pages", models.CharField(blank=True, max_length=64, verbose_name="Pages")),
                ("urls", models.TextField(blank=True, verbose_name="URLs")),
                ("abstract", ckeditor.fields.RichTextField(blank=True, verbose_name="Résumé")),
                ("isbn", models.CharField(blank=True, max_length=24, verbose_name="ISBN")),
                ("serie", models.CharField(blank=True, max_length=64, verbose_name="Série")),
                ("serie_num", models.CharField(blank=True, max_length=64, verbose_name="N° de la série")),
                ("cote", models.CharField(blank=True, max_length=150, verbose_name="Cote")),
                ("authorization", models.BooleanField(blank=True, default=False, verbose_name="Autorisation")),
                ("access_date", models.DateField(blank=True, null=True, verbose_name="Accédé le")),
                ("extra", models.CharField(blank=True, max_length=128, verbose_name="Extra")),
                ("first_author_name", models.CharField(blank=True, default="", editable=False, max_length=215)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Auteur de la fiche",
                    ),
                ),
                (
                    "subj_secondary_kw",
                    models.ManyToManyField(
                        blank=True, to="fiches.secondarykeyword", verbose_name="Mot clé secondaire"
                    ),
                ),
                (
                    "depot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="fiches.depot",
                        verbose_name="Lieu de dépôt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fiche bibliographique",
                "verbose_name_plural": "Fiches bibliographiques",
                "ordering": ["first_author_name", "title"],
                "permissions": (
                    ("change_biblio_ownership", "Can change ownership of Bibliography"),
                    ("change_any_biblio", "Can change any Bibliography"),
                    ("delete_any_biblio", "Can delete any Bibliography"),
                    ("can_add_listitem", "Can add item in autocomplete lists"),
                ),
            },
        ),
        migrations.CreateModel(
            name="ManuscriptB",
            fields=[],
            options={
                "verbose_name": "Fiche de manuscrit",
                "verbose_name_plural": "Fiches de manuscrit",
                "ordering": ("title", "-date"),
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("fiches.biblio",),
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(blank=True, max_length=250, verbose_name="Titre")),
                ("file", models.FileField(upload_to="files/%Y/%m", verbose_name="Fichier")),
                ("object_id", models.PositiveIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "access_public",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="L'élément sera visible par tout le monde.",
                        verbose_name="Public",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255)),
                ("file", models.FileField(blank=True, null=True, upload_to="documents/")),
                ("url", models.URLField(blank=True, null=True)),
                (
                    "access_owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Propriétaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fichier",
                "verbose_name_plural": "Fichiers",
                "db_table": "fiches_documentfile",
            },
        ),
        migrations.AddField(
            model_name="biblio",
            name="documentfiles",
            field=models.ManyToManyField(blank=True, to="fiches.documentfile"),
        ),
        migrations.AddField(
            model_name="biblio",
            name="language",
            field=models.ForeignKey(
                default=fiches.models.documents.document.get_default_language,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="fiches.documentlanguage",
                verbose_name="Langue",
            ),
        ),
        migrations.AddField(
            model_name="biblio",
            name="language_sec",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sec_biblio_set",
                to="fiches.documentlanguage",
                verbose_name="Langue secondaire",
            ),
        ),
        migrations.AddField(
            model_name="biblio",
            name="document_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="fiches.documenttype", verbose_name="Type de document"
            ),
        ),
        migrations.CreateModel(
            name="Finding",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("created_on", models.DateTimeField(auto_now_add=True, verbose_name="créé le")),
                ("modified_on", models.DateTimeField(auto_now=True, verbose_name="modifié le")),
                (
                    "published",
                    models.BooleanField(
                        default=False, help_text="Cocher pour donner un accès public.", verbose_name="Publié"
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                ("thumbnail", sorl.thumbnail.fields.ImageField(upload_to="images/%Y/%m", verbose_name="Vignette")),
                ("content", ckeditor.fields.RichTextField(verbose_name="Contenu")),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Auteur",
                    ),
                ),
                (
                    "author2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="finding_set2",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="2e auteur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trouvaille",
                "ordering": ["-created_on"],
            },
        ),
        migrations.CreateModel(
            name="FreeContent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, unique=True, verbose_name="Nom")),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("created_on", models.DateTimeField(auto_now_add=True, verbose_name="créé le")),
                ("modified_on", models.DateTimeField(auto_now=True, verbose_name="modifié le")),
                ("content", ckeditor.fields.RichTextField(blank=True, verbose_name="Contenu")),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Auteur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contenu libre",
                "verbose_name_plural": "Contenus libres",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("legend", models.TextField(blank=True, verbose_name="Légende")),
                ("image", models.ImageField(upload_to="images/%Y/%m")),
                ("link", models.URLField(blank=True, verbose_name="Lien")),
                ("pos", models.IntegerField(blank=True, null=True, verbose_name="Position")),
                ("object_id", models.PositiveIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
                ),
            ],
            options={
                "ordering": ("pos",),
            },
        ),
        migrations.CreateModel(
            name="Manuscript",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=512, verbose_name="Titre")),
                ("short_title", models.CharField(blank=True, max_length=512, verbose_name="Titre court")),
                ("inscription", models.CharField(blank=True, max_length=256)),
                ("abstract", models.TextField(blank=True, verbose_name="Résumé")),
                ("place", models.CharField(blank=True, max_length=256, verbose_name="Lieu")),
                ("date", models.DateField(blank=True, null=True, verbose_name="Date")),
                ("date_f", models.CharField(blank=True, max_length=15, null=True)),
                ("pages", models.CharField(blank=True, max_length=128, null=True, verbose_name="Pages")),
                ("urls", models.TextField(blank=True, verbose_name="URLs")),
                ("access_date", models.DateField(blank=True, null=True, verbose_name="Accédé le")),
                ("depot", models.CharField(blank=True, max_length=128, verbose_name="Lieu de dépôt")),
                ("cote", models.CharField(blank=True, max_length=150, verbose_name="Cote")),
                (
                    "authorization",
                    models.BooleanField(blank=True, default=False, null=True, verbose_name="Autorisation"),
                ),
                ("extra", models.CharField(blank=True, max_length=128, verbose_name="Extra")),
                (
                    "biblio_man",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="fiches.biblio"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Auteur de la fiche",
                    ),
                ),
                ("documentfiles", models.ManyToManyField(blank=True, to="fiches.documentfile")),
                (
                    "lang_main",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manuscript_main_set",
                        to="fiches.documentlanguage",
                        verbose_name="Langue principale",
                    ),
                ),
                (
                    "lang_sec",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manuscript_sec_set",
                        to="fiches.documentlanguage",
                        verbose_name="Langue secondaire",
                    ),
                ),
                (
                    "subj_secondary_kw",
                    models.ManyToManyField(
                        blank=True, to="fiches.secondarykeyword", verbose_name="Mot clé secondaire"
                    ),
                ),
                (
                    "manuscript_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="fiches.manuscripttype",
                        verbose_name="Type",
                    ),
                ),
                (
                    "first_author",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="fiches.person",
                        verbose_name="Premier Auteur",
                    ),
                ),
                (
                    "subj_primary_kw",
                    models.ManyToManyField(blank=True, to="fiches.primarykeyword", verbose_name="Mot clé principal"),
                ),
                ("subj_society", models.ManyToManyField(blank=True, to="fiches.society", verbose_name="Société")),
            ],
            options={
                "verbose_name": "Fiche de manuscrit",
                "verbose_name_plural": "Fiches de manuscrit",
                "ordering": ("title", "-date"),
                "permissions": (
                    ("change_manuscript_ownership", "Can change ownership of Manuscript"),
                    ("change_any_manuscript", "Can change any Manuscript"),
                    ("delete_any_manuscript", "Can delete any Manuscript"),
                ),
            },
        ),
        migrations.AddField(
            model_name="biblio",
            name="manuscript_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="fiches.manuscripttype",
                verbose_name="Type d'écrit",
            ),
        ),
        migrations.CreateModel(
            name="Biography",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version", models.IntegerField(default=0, editable=False)),
                ("valid", models.BooleanField(default=False)),
                ("birth_place", models.CharField(blank=True, max_length=256, verbose_name="Lieu de naissance")),
                ("birth_date", models.DateField(blank=True, null=True, verbose_name="Date de naissance")),
                ("birth_date_f", models.CharField(blank=True, max_length=15)),
                (
                    "birth_date_approx",
                    models.BooleanField(default=False, verbose_name="Date de naissance approximative"),
                ),
                ("death_place", models.CharField(blank=True, max_length=256, verbose_name="Lieu de décès")),
                ("death_date", models.DateField(blank=True, null=True, verbose_name="Date de décès")),
                ("death_date_f", models.CharField(blank=True, max_length=15)),
                ("death_date_approx", models.BooleanField(default=False, verbose_name="Date de décès approximative")),
                ("origin", models.CharField(blank=True, max_length=512, verbose_name="Lieu d'origine")),
                (
                    "education",
                    models.TextField(
                        blank=True, help_text="NE PAS REMPLIR CE CHAMP!", null=True, verbose_name="Formation"
                    ),
                ),
                ("public_functions", ckeditor.fields.RichTextField(blank=True, null=True, verbose_name="Biographie")),
                (
                    "comments_on_work",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="Commentaires sur son oeuvre/ses écrits"
                    ),
                ),
                ("activity_places", models.TextField(blank=True, null=True, verbose_name="Etat civil")),
                (
                    "abroad_stays",
                    models.TextField(
                        blank=True,
                        help_text="NE PAS REMPLIR CE CHAMP!",
                        null=True,
                        verbose_name="Séjours à l'étranger",
                    ),
                ),
                (
                    "archive",
                    ckeditor.fields.RichTextField(blank=True, max_length=512, verbose_name="Fonds d'archives"),
                ),
                ("modification_date", models.DateTimeField(auto_now=True, verbose_name="Dernière modification")),
                (
                    "nationality",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="fiches.nationality",
                        verbose_name="Nationalité",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fiches.person",
                        verbose_name="Personne",
                    ),
                ),
                (
                    "religion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="fiches.religion",
                        verbose_name="Confession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fiche biographique",
                "verbose_name_plural": "Fiches biographiques",
                "permissions": (
                    ("validate_biography", "Can validate"),
                    ("browse_biography_versions", "Can browse versions"),
                    ("access_unvalidated_biography", "Can see not validated Biography"),
                ),
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("created_on", models.DateTimeField(auto_now_add=True, verbose_name="créé le")),
                ("modified_on", models.DateTimeField(auto_now=True, verbose_name="modifié le")),
                (
                    "published",
                    models.BooleanField(
                        default=False, help_text="Cocher pour donner un accès public.", verbose_name="Publié"
                    ),
                ),
                ("content", ckeditor.fields.RichTextField(verbose_name="Contenu")),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Auteur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Actualité",
                "ordering": ["-created_on"],
            },
        ),
        migrations.CreateModel(
            name="ContributionDoc",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("in_brackets", models.BooleanField(default=False, verbose_name="Entre crochets")),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fiches.biblio",
                        verbose_name="Biblio",
                    ),
                ),
                (
                    "contribution_type",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"type__in": ["doc", "any"]},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="fiches.contributiontype",
                        verbose_name="Type de contribution",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contribution_biblio",
                        to="fiches.person",
                        verbose_name="Contributeur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contribution pour Document",
                "verbose_name_plural": "Contributions pour Document",
                "ordering": ("contribution_type", "person"),
            },
        ),
        migrations.AddField(
            model_name="biblio",
            name="first_author",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="biblio_asfirstauthor_set",
                to="fiches.person",
                verbose_name="Premier Auteur",
            ),
        ),
        migrations.AddField(
            model_name="biblio",
            name="subj_person",
            field=models.ManyToManyField(blank=True, to="fiches.person", verbose_name="Personne"),
        ),
        migrations.AddField(
            model_name="biblio",
            name="subj_primary_kw",
            field=models.ManyToManyField(blank=True, to="fiches.primarykeyword", verbose_name="Mot clé principal"),
        ),
        migrations.CreateModel(
            name="Profession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("begin_date", models.DateField(blank=True, null=True, verbose_name="Début")),
                ("begin_date_f", models.CharField(blank=True, max_length=15, null=True)),
                ("begin_date_approx", models.BooleanField(default=False, verbose_name="Date de début approximative")),
                ("end_date", models.DateField(blank=True, null=True, verbose_name="Fin")),
                ("end_date_f", models.CharField(blank=True, max_length=15, null=True)),
                ("end_date_approx", models.BooleanField(default=False, verbose_name="Date de fin approximative")),
                ("position", models.CharField(max_length=256, verbose_name="Poste")),
                ("place", models.CharField(blank=True, max_length=256, verbose_name="Lieu")),
                ("bio", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="fiches.biography")),
            ],
            options={
                "ordering": ("begin_date", "end_date"),
            },
        ),
        migrations.CreateModel(
            name="Relation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bio", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="fiches.biography")),
                (
                    "related_person",
                    models.ForeignKey(
                        limit_choices_to={"modern": False},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="person_back",
                        to="fiches.person",
                        verbose_name="Personne",
                    ),
                ),
                (
                    "relation_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fiches.relationtype",
                        verbose_name="Type de relation",
                    ),
                ),
            ],
            options={
                "ordering": ("relation_type__sorting",),
            },
        ),
        migrations.CreateModel(
            name="ReverseRelation",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("fiches.relation",),
        ),
        migrations.CreateModel(
            name="SearchFilters",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=30, verbose_name="Titre")),
                ("model_name", models.CharField(max_length=30)),
                ("query_def", models.TextField(blank=True)),
                ("display_columns", models.TextField(blank=True)),
                ("display_settings", utils.fields.DictField(blank=True)),
                ("groups", models.ManyToManyField(blank=True, to="auth.group")),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Filtre de recherche",
                "verbose_name_plural": "Filtre de recherche",
            },
        ),
        migrations.AddField(
            model_name="biblio",
            name="subj_society",
            field=models.ManyToManyField(blank=True, to="fiches.society", verbose_name="Société/Académie"),
        ),
        migrations.CreateModel(
            name="SocietyMembership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("begin_date", models.DateField(blank=True, null=True, verbose_name="Début")),
                ("begin_date_f", models.CharField(blank=True, max_length=15, null=True)),
                ("begin_date_approx", models.BooleanField(default=False, verbose_name="Date de début approximative")),
                ("end_date", models.DateField(blank=True, null=True, verbose_name="Fin")),
                ("end_date_f", models.CharField(blank=True, max_length=15, null=True)),
                ("end_date_approx", models.BooleanField(default=False, verbose_name="Date de fin approximative")),
                ("bio", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="fiches.biography")),
                (
                    "society",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="fiches.society", verbose_name="Société"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transcription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "access_public",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="L'élément sera visible par tout le monde.",
                        verbose_name="Public",
                    ),
                ),
                ("cite_author", models.BooleanField(blank=True, default=False, verbose_name="Citer l'auteur")),
                ("cite_author2", models.BooleanField(blank=True, default=False, verbose_name="Citer le 2e auteur")),
                (
                    "status",
                    models.IntegerField(choices=[(0, "En cours"), (1, "Fini")], default=0, verbose_name="État"),
                ),
                (
                    "scope",
                    models.IntegerField(
                        choices=[(0, "Intégrale"), (1, "Extrait")], default=0, verbose_name="Transcription"
                    ),
                ),
                ("text", ckeditor.fields.RichTextField(blank=True)),
                ("envelope", ckeditor.fields.RichTextField(blank=True, verbose_name="Enveloppe")),
                (
                    "facsimile_iiif_url",
                    models.URLField(
                        blank=True,
                        help_text="URL du manifeste IIIF (par ex. se terminant par info.json).",
                        verbose_name="URL IIIF du facsimilé",
                    ),
                ),
                (
                    "facsimile_start_canvas",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="Page de départ du facsimilé"),
                ),
                ("access_private", models.BooleanField(blank=True, default=True, verbose_name="Privé")),
                (
                    "access_owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Propriétaire",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transcriptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Auteur",
                    ),
                ),
                (
                    "author2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transcriptions2",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="2e auteur",
                    ),
                ),
                (
                    "manuscript",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="fiches.manuscript"
                    ),
                ),
                (
                    "manuscript_b",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="fiches.biblio"
                    ),
                ),
            ],
            options={
                "verbose_name": "Fiche de transcription",
                "verbose_name_plural": "Fiches de transcription",
                "ordering": ["manuscript_b__title"],
                "permissions": (
                    ("change_transcription_ownership", "Can change ownership of Transcription"),
                    ("change_any_transcription", "Can change any Transcription"),
                    ("delete_any_transcription", "Can delete any Transcription"),
                    ("publish_transcription", "Can Publish Transcription"),
                    ("access_unpublished_transcription", "Can Access Unpublished Transcription"),
                ),
            },
        ),
        migrations.CreateModel(
            name="TranscriptionReviewer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "transcription",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="fiches.transcription"),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "fiches_transcription_reviewers",
            },
        ),
        migrations.CreateModel(
            name="UserGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=125, verbose_name="Nom")),
                ("description", models.TextField(blank=True, verbose_name="Description")),
                ("sort", models.IntegerField(blank=True, verbose_name="ordre de tri")),
                ("groups", models.ManyToManyField(blank=True, to="auth.group", verbose_name="Groupes")),
                (
                    "users",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name="Utilisateurs"),
                ),
            ],
            options={
                "verbose_name": "Groupe d'utilisateurs",
                "verbose_name_plural": "Groupes d'utilisateurs",
                "ordering": ["sort"],
            },
        ),
        migrations.AddField(
            model_name="transcription",
            name="access_groups",
            field=models.ManyToManyField(blank=True, to="fiches.usergroup", verbose_name="Groupes d'accès"),
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=125, verbose_name="Nom")),
                (
                    "url",
                    models.SlugField(
                        help_text="ATTENTION, doit être unique. Uniquement caractères non-accentués, tiret et chiffres. Pas d'espaces ni de ponctuation.",
                        unique=True,
                        verbose_name="Url",
                    ),
                ),
                ("description", ckeditor.fields.RichTextField(blank=True, verbose_name="Description")),
                (
                    "short_desc",
                    models.CharField(
                        blank=True,
                        help_text="Texte utilisé dans la liste des projets. <strong>250 signes maximum.</strong> Si le champ est vide, le texte de description normal sera utilisé, tronqué à 250 signes",
                        max_length=250,
                        verbose_name="Description courte",
                    ),
                ),
                ("image", models.ImageField(blank=True, upload_to="user_uploads/%Y/%m", verbose_name="Vignette")),
                (
                    "publish",
                    models.BooleanField(
                        default=False,
                        help_text="Cocher pour donner un accès public. Sinon, accès limité au propriétaire et aux membres",
                        verbose_name="Publié",
                    ),
                ),
                ("bibliographies", models.ManyToManyField(blank=True, to="fiches.biblio")),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True, related_name="member_projects", to=settings.AUTH_USER_MODEL, verbose_name="Membres"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Propriétaire",
                    ),
                ),
                ("persons", models.ManyToManyField(blank=True, related_name="projects", to="fiches.person")),
                ("transcriptions", models.ManyToManyField(blank=True, to="fiches.transcription")),
                (
                    "access_groups",
                    models.ManyToManyField(
                        blank=True, related_name="group_projects", to="fiches.usergroup", verbose_name="Groupes"
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ["id"],
                "permissions": (("view_unpublished_project", "Peut voir un projet non publié"),),
            },
        ),
        migrations.CreateModel(
            name="ObjectCollection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "access_public",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="L'élément sera visible par tout le monde.",
                        verbose_name="Public",
                    ),
                ),
                ("name", models.CharField(max_length=125, verbose_name="Nom de la collection")),
                ("slug", models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ("description", models.TextField(blank=True, verbose_name="Description")),
                (
                    "access_private",
                    models.BooleanField(
                        blank=True,
                        default=True,
                        help_text="Accessible pour le propriétaire seulement",
                        verbose_name="Privé",
                    ),
                ),
                (
                    "access_owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Propriétaire",
                    ),
                ),
                ("bibliographies", models.ManyToManyField(blank=True, to="fiches.biblio")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="objectcollections",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
                ("persons", models.ManyToManyField(blank=True, related_name="objectcollections", to="fiches.person")),
                ("transcriptions", models.ManyToManyField(blank=True, to="fiches.transcription")),
                (
                    "access_groups",
                    models.ManyToManyField(blank=True, to="fiches.usergroup", verbose_name="Groupes d'accès"),
                ),
                (
                    "change_groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="objectcollections",
                        to="fiches.usergroup",
                        verbose_name="Groupes contributeurs",
                    ),
                ),
            ],
            options={
                "verbose_name": "Collection",
                "verbose_name_plural": "Collections",
                "ordering": ["id"],
                "permissions": [("change_collection_owner", "Peut changer le propriétaire de la collection")],
            },
        ),
        migrations.CreateModel(
            name="NoteTranscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "access_public",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="L'élément sera visible par tout le monde.",
                        verbose_name="Public",
                    ),
                ),
                ("text", ckeditor.fields.RichTextField(blank=True, verbose_name="Note")),
                (
                    "access_owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Propriétaire",
                    ),
                ),
                ("groups", models.ManyToManyField(blank=True, to="auth.group", verbose_name="Visible pour")),
                (
                    "owner",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="fiches.transcription"
                    ),
                ),
                (
                    "access_groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Contrôle d'accès par groupe utilisateur",
                        to="fiches.usergroup",
                        verbose_name="Groupes d'accès",
                    ),
                ),
            ],
            options={
                "permissions": (("can_see_note", "Can see Note"), ("can_publish_note", "Can publish note")),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NoteManuscript",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "access_public",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="L'élément sera visible par tout le monde.",
                        verbose_name="Public",
                    ),
                ),
                ("text", ckeditor.fields.RichTextField(blank=True, verbose_name="Note")),
                (
                    "access_owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Propriétaire",
                    ),
                ),
                ("groups", models.ManyToManyField(blank=True, to="auth.group", verbose_name="Visible pour")),
                (
                    "owner",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="fiches.manuscript"),
                ),
                (
                    "access_groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Contrôle d'accès par groupe utilisateur",
                        to="fiches.usergroup",
                        verbose_name="Groupes d'accès",
                    ),
                ),
            ],
            options={
                "permissions": (("can_see_note", "Can see Note"), ("can_publish_note", "Can publish note")),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NoteBiography",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "access_public",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="L'élément sera visible par tout le monde.",
                        verbose_name="Public",
                    ),
                ),
                ("text", ckeditor.fields.RichTextField(blank=True, verbose_name="Note")),
                (
                    "access_owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Propriétaire",
                    ),
                ),
                ("groups", models.ManyToManyField(blank=True, to="auth.group", verbose_name="Visible pour")),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="fiches.biography")),
                (
                    "access_groups",
                    models.ManyToManyField(blank=True, to="fiches.usergroup", verbose_name="Groupes d'accès"),
                ),
            ],
            options={
                "permissions": (("can_see_note", "Can see Note"), ("can_publish_note", "Can publish note")),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NoteBiblio",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "access_public",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="L'élément sera visible par tout le monde.",
                        verbose_name="Public",
                    ),
                ),
                ("text", ckeditor.fields.RichTextField(blank=True, verbose_name="Note")),
                (
                    "access_owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Propriétaire",
                    ),
                ),
                ("groups", models.ManyToManyField(blank=True, to="auth.group", verbose_name="Visible pour")),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notes",
                        to="fiches.biblio",
                    ),
                ),
                (
                    "access_groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Contrôle d'accès par groupe utilisateur",
                        to="fiches.usergroup",
                        verbose_name="Groupes d'accès",
                    ),
                ),
            ],
            options={
                "permissions": (("can_see_note", "Can see Note"), ("can_publish_note", "Can publish note")),
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="documentfile",
            name="access_groups",
            field=models.ManyToManyField(blank=True, to="fiches.usergroup", verbose_name="Groupes d'accès"),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("field_of_research", models.TextField(blank=True, verbose_name="Domaine de recherche / Historique")),
                ("shib_uniqueID", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Informations supplémentaires",
                "verbose_name_plural": "Informations supplémentaires",
            },
        ),
        migrations.CreateModel(
            name="ContributionMan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "contribution_type",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"type__in": ["man", "any"]},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contribution_mans_types",
                        to="fiches.contributiontype",
                        verbose_name="Type de contribution",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contribution_mans_documents",
                        to="fiches.manuscript",
                        verbose_name="Manuscrit",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contribution_mans",
                        to="fiches.person",
                        verbose_name="Contributeur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contribution pour Manuscrit",
                "verbose_name_plural": "Contributions pour Manuscrit",
                "unique_together": {("person", "document", "contribution_type")},
            },
        ),
    ]
