# Generated by Django 5.2 on 2026-02-12 08:00

from django.db import migrations


def populate_transcription_dates(apps, schema_editor):
    """
    Populate published_date and modified_date from ActivityLog.

    - For public transcriptions: set published_date to first activity date
    - For all transcriptions: set modified_date to last activity date

    Optimized version using raw SQL for better performance.
    """
    from django.db import connection

    with connection.cursor() as cursor:
        # First, update modified_date to the last activity date for each transcription
        cursor.execute("""
            UPDATE fiches_transcription AS t
            INNER JOIN (
                SELECT object_id, MAX(date) AS last_date
                FROM fiches_activitylog
                WHERE model_name = 'Transcription'
                GROUP BY object_id
            ) AS last_activity ON t.id = last_activity.object_id
            SET t.modified_date = last_activity.last_date
        """)

        # Second, update published_date to the first activity date for public transcriptions
        cursor.execute("""
            UPDATE fiches_transcription AS t
            INNER JOIN (
                SELECT object_id, MIN(date) AS first_date
                FROM fiches_activitylog
                WHERE model_name = 'Transcription'
                GROUP BY object_id
            ) AS first_activity ON t.id = first_activity.object_id
            SET t.published_date = first_activity.first_date
            WHERE t.access_public = 1 AND t.published_date IS NULL
        """)


def reverse_migration(apps, schema_editor):
    """
    Reverse operation: clear the populated dates.
    """
    Transcription = apps.get_model("fiches", "Transcription")
    Transcription.objects.all().update(published_date=None)
    # Note: modified_date will be auto-set on save due to auto_now


class Migration(migrations.Migration):
    dependencies = [
        ("fiches", "0002_add_transcription_date_fields"),
    ]

    operations = [
        migrations.RunPython(populate_transcription_dates, reverse_migration),
    ]

    operations = [
        migrations.RunPython(populate_transcription_dates, reverse_migration),
    ]
