# Generated by Django 5.2.14 on 2026-05-29 06:03

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fiches", "0003_populate_transcription_dates"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="transcription",
            name="modified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="modified_transcriptions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Dernière modification par",
            ),
        ),
        migrations.AddField(
            model_name="transcription",
            name="published_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="published_transcriptions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Mise en ligne par",
            ),
        ),
        migrations.AlterField(
            model_name="biography",
            name="archive",
            field=ckeditor.fields.RichTextField(blank=True, verbose_name="Fonds d'archives"),
        ),
        migrations.AlterField(
            model_name="transcription",
            name="modified_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date de modification"),
        ),
    ]
