# Generated by Django 5.2.14 on 2026-06-16 11:08

from django.db import migrations, models

INITIAL_CATEGORIES = [
    "Pays",
    "Canton/Département",
    "Région",
    "Ville/Village",
    "Domaine",
    "Maison de campagne",
    "Quartier",
]


def seed_categories(apps, schema_editor):
    """Populate the category lookup with the default categories (idempotent)."""
    PlaceCategory = apps.get_model("fiches", "PlaceCategory")
    for name in INITIAL_CATEGORIES:
        PlaceCategory.objects.get_or_create(name=name)


def unseed_categories(apps, schema_editor):
    """Remove the seeded default categories."""
    PlaceCategory = apps.get_model("fiches", "PlaceCategory")
    PlaceCategory.objects.filter(name__in=INITIAL_CATEGORIES).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("fiches", "0006_drop_legacy_contenttype_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlaceCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128, unique=True, verbose_name="Nom")),
            ],
            options={
                "verbose_name": "Catégorie de lieu",
                "verbose_name_plural": "Catégories de lieux",
                "ordering": ("name",),
            },
        ),
        migrations.RunPython(seed_categories, unseed_categories),
    ]
