# Generated by Django 5.2.14 on 2026-06-16 13:28

from django.db import migrations, models

REFERENCE_SITES = [
    {"name": "GeoNames", "code": "geonames", "base_url": "https://www.geonames.org/{id}"},
    {"name": "Wikidata", "code": "wikidata", "base_url": "https://www.wikidata.org/wiki/{id}"},
    {"name": "DHS", "code": "dhs", "base_url": "https://hls-dhs-dss.ch/fr/articles/{id}/"},
    {"name": "VIAF", "code": "viaf", "base_url": "https://viaf.org/viaf/{id}"},
    {"name": "IdRef", "code": "idref", "base_url": "https://www.idref.fr/{id}"},
    {"name": "GND", "code": "gnd", "base_url": "https://d-nb.info/gnd/{id}"},
]


def seed_reference_sites(apps, schema_editor):
    """Populate the reference-site catalog with the default référentiels (idempotent)."""
    ReferenceSite = apps.get_model("fiches", "ReferenceSite")
    for site in REFERENCE_SITES:
        ReferenceSite.objects.get_or_create(
            code=site["code"],
            defaults={"name": site["name"], "base_url": site["base_url"]},
        )


def unseed_reference_sites(apps, schema_editor):
    """Remove the seeded default référentiels."""
    ReferenceSite = apps.get_model("fiches", "ReferenceSite")
    ReferenceSite.objects.filter(code__in=[site["code"] for site in REFERENCE_SITES]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("fiches", "0007_placecategory"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferenceSite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=64, unique=True, verbose_name="Nom du référentiel")),
                (
                    "code",
                    models.SlugField(
                        help_text="Identifiant court, ex: geonames, wikidata, dhs, viaf, idref",
                        max_length=32,
                        unique=True,
                        verbose_name="Code",
                    ),
                ),
                (
                    "base_url",
                    models.URLField(
                        blank=True,
                        help_text=(
                            "Gabarit avec le marqueur {id} pour générer le permalien à partir de "
                            "l'identifiant (ex: https://www.geonames.org/{id}). Sans {id}, traité "
                            "comme préfixe."
                        ),
                        verbose_name="Gabarit d'URL",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
            ],
            options={
                "verbose_name": "Site de référence",
                "verbose_name_plural": "Sites de référence",
                "ordering": ("name",),
            },
        ),
        migrations.RunPython(seed_reference_sites, unseed_reference_sites),
    ]
