# Generated by Django 5.2.14 on 2026-06-17 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fiches", "0008_referencesite"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlaceRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "access_public",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="L'élément sera visible par tout le monde.",
                        verbose_name="Public",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nom")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Créé le")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Mis à jour le")),
                (
                    "access_groups",
                    models.ManyToManyField(
                        blank=True, db_constraint=False, to="fiches.usergroup", verbose_name="Groupes d'accès"
                    ),
                ),
                (
                    "access_owner",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Propriétaire",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="places",
                        to="fiches.placecategory",
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "related_places",
                    models.ManyToManyField(blank=True, to="fiches.placerecord", verbose_name="Lieux associés"),
                ),
            ],
            options={
                "verbose_name": "Fiche lieu",
                "verbose_name_plural": "Fiches lieux",
                "ordering": ("name",),
                "constraints": [
                    models.UniqueConstraint(fields=("name", "category"), name="unique_place_name_per_category")
                ],
            },
        ),
    ]
