# Generated by Django 5.2.14 on 2026-06-17 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fiches", "0009_placerecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlaceVariant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Variante")),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="fiches.placerecord",
                        verbose_name="Lieu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Variante de lieu",
                "verbose_name_plural": "Variantes de lieu",
                "ordering": ("name",),
                "constraints": [models.UniqueConstraint(fields=("place", "name"), name="unique_variant_per_place")],
            },
        ),
    ]
