# Generated by Django 5.2.14 on 2026-06-18 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fiches", "0010_placevariant"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlaceReferenceSite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("identifier", models.CharField(max_length=255, verbose_name="Identifiant")),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reference_links",
                        to="fiches.placerecord",
                        verbose_name="Lieu",
                    ),
                ),
                (
                    "reference_site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="place_links",
                        to="fiches.referencesite",
                        verbose_name="Site de référence",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site de référence du lieu",
                "verbose_name_plural": "Sites de référence du lieu",
                "ordering": ("reference_site__name",),
                "constraints": [
                    models.UniqueConstraint(fields=("place", "reference_site"), name="unique_reference_site_per_place")
                ],
            },
        ),
    ]
