# Generated by Django 5.2.14 on 2026-06-23 07:24

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("fiches", "0011_placereferencesite"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotePlace",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "access_public",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="L'élément sera visible par tout le monde.",
                        verbose_name="Public",
                    ),
                ),
                ("text", ckeditor.fields.RichTextField(blank=True, verbose_name="Note")),
                (
                    "access_groups",
                    models.ManyToManyField(
                        blank=True, db_constraint=False, to="fiches.usergroup", verbose_name="Groupes d'accès"
                    ),
                ),
                (
                    "access_owner",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Propriétaire",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True, db_constraint=False, to="auth.group", verbose_name="Visible pour"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="fiches.placerecord",
                        verbose_name="Lieu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Note de lieu",
                "verbose_name_plural": "Notes de lieu",
                "permissions": (("can_see_note", "Can see Note"), ("can_publish_note", "Can publish note")),
                "abstract": False,
            },
        ),
    ]
