# Generated by Django 5.2.14 on 2026-06-26 13:39

from django.db import migrations, models

# Which fiche types may link to each seeded référentiel.
# Persons: DHS, IdRef, GND, VIAF, Wikidata. Places: GeoNames, Wikidata, DHS.
APPLICABILITY = {
    "geonames": {"applies_to_person": False, "applies_to_place": True},
    "wikidata": {"applies_to_person": True, "applies_to_place": True},
    "dhs": {"applies_to_person": True, "applies_to_place": True},
    "viaf": {"applies_to_person": True, "applies_to_place": False},
    "idref": {"applies_to_person": True, "applies_to_place": False},
    "gnd": {"applies_to_person": True, "applies_to_place": False},
}


def set_applicability(apps, schema_editor):
    """Flag the seeded référentiels with the fiche types that may link to them."""
    ReferenceSite = apps.get_model("fiches", "ReferenceSite")
    for code, flags in APPLICABILITY.items():
        ReferenceSite.objects.filter(code=code).update(**flags)


def reset_applicability(apps, schema_editor):
    """Reset the seeded référentiels to the permissive default (both true)."""
    ReferenceSite = apps.get_model("fiches", "ReferenceSite")
    ReferenceSite.objects.filter(code__in=APPLICABILITY).update(applies_to_person=True, applies_to_place=True)


class Migration(migrations.Migration):
    dependencies = [
        ("fiches", "0012_noteplace"),
    ]

    operations = [
        migrations.AddField(
            model_name="referencesite",
            name="applies_to_person",
            field=models.BooleanField(
                default=True,
                help_text="Proposer ce référentiel dans les fiches biographiques.",
                verbose_name="Pour les personnes",
            ),
        ),
        migrations.AddField(
            model_name="referencesite",
            name="applies_to_place",
            field=models.BooleanField(
                default=True,
                help_text="Proposer ce référentiel dans les fiches de lieux.",
                verbose_name="Pour les lieux",
            ),
        ),
        migrations.RunPython(set_applicability, reset_applicability),
    ]
