# Generated by Django 5.2.14 on 2026-06-26 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fiches", "0013_reference_site_applicability_flags"),
    ]

    operations = [
        migrations.CreateModel(
            name="BiographyReferenceSite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("identifier", models.CharField(max_length=255, verbose_name="Identifiant")),
                (
                    "biography",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reference_links",
                        to="fiches.biography",
                        verbose_name="Biographie",
                    ),
                ),
                (
                    "reference_site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="biography_links",
                        to="fiches.referencesite",
                        verbose_name="Site de référence",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site de référence de la biographie",
                "verbose_name_plural": "Sites de référence de la biographie",
                "ordering": ("reference_site__name",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("biography", "reference_site"), name="unique_reference_site_per_biography"
                    )
                ],
            },
        ),
    ]
