# Generated by Django 5.2.14 on 2026-06-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0014_biography_reference_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biography',
            name='birth_place',
            field=models.TextField(blank=True, verbose_name='Lieu de naissance'),
        ),
        migrations.AlterField(
            model_name='biography',
            name='death_place',
            field=models.TextField(blank=True, verbose_name='Lieu de décès'),
        ),
        migrations.AlterField(
            model_name='biography',
            name='origin',
            field=models.TextField(blank=True, verbose_name="Lieu d'origine"),
        ),
        migrations.AlterField(
            model_name='profession',
            name='place',
            field=models.TextField(blank=True, verbose_name='Lieu'),
        ),
    ]
