# Generated by Django 5.2.14 on 2026-06-30 06:24

from django.db import migrations, models

# "Lieu de destination" is shown only for manuscripts, via the DocumentType
# exclusive_fields mechanism (cf. edition/bibliographie.html show/hide).
MANUSCRIPT_TYPE_NAME = "Manuscrit"
DESTINATION_FIELD = "destination"


def _exclusive_fields(value):
    return [f.strip() for f in (value or "").split(",") if f.strip()]


def add_destination_exclusive(apps, schema_editor):
    """Attach the new "destination" field to the manuscript document type."""
    DocumentType = apps.get_model("fiches", "DocumentType")
    for doctype in DocumentType.objects.filter(name=MANUSCRIPT_TYPE_NAME):
        fields = _exclusive_fields(doctype.exclusive_fields)
        if DESTINATION_FIELD not in fields:
            fields.append(DESTINATION_FIELD)
            doctype.exclusive_fields = ",".join(fields)
            doctype.save(update_fields=["exclusive_fields"])


def remove_destination_exclusive(apps, schema_editor):
    """Reverse: detach "destination" from the manuscript document type."""
    DocumentType = apps.get_model("fiches", "DocumentType")
    for doctype in DocumentType.objects.filter(name=MANUSCRIPT_TYPE_NAME):
        fields = [f for f in _exclusive_fields(doctype.exclusive_fields) if f != DESTINATION_FIELD]
        doctype.exclusive_fields = ",".join(fields)
        doctype.save(update_fields=["exclusive_fields"])


class Migration(migrations.Migration):
    dependencies = [
        ("fiches", "0015_place_fields_to_textfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="biblio",
            name="destination",
            field=models.TextField(blank=True, verbose_name="Lieu de destination"),
        ),
        migrations.AlterField(
            model_name="biblio",
            name="place",
            field=models.TextField(blank=True, verbose_name="Lieu"),
        ),
        migrations.AlterField(
            model_name="biblio",
            name="place2",
            field=models.TextField(blank=True, verbose_name="2e Lieu"),
        ),
        migrations.RunPython(add_destination_exclusive, remove_destination_exclusive),
    ]
