# Generated by Django 5.2.14 on 2026-06-30 07:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fiches", "0016_biblio_place_tagging"),
    ]

    operations = [
        migrations.AddField(
            model_name="biblio",
            name="subj_place",
            field=models.ManyToManyField(
                blank=True, db_constraint=False, to="fiches.placerecord", verbose_name="Lieu"
            ),
        ),
    ]
