# Generated by Django 5.2.14 on 2026-06-30 12:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fiches", "0017_biblio_subj_place"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="placerecord",
            options={"ordering": ("name",), "verbose_name": "Lieu", "verbose_name_plural": "Lieux"},
        ),
    ]
