# Generated by Django 5.2.14 on 2026-06-30 13:06

import django.db.models.deletion
from django.db import migrations, models

# "Nature du document" is shown only for manuscripts, via the DocumentType
# exclusive_fields mechanism (cf. 0016 for "destination").
MANUSCRIPT_TYPE_NAME = "Manuscrit"
NATURE_FIELD = "document_nature"


def _exclusive_fields(value):
    return [f.strip() for f in (value or "").split(",") if f.strip()]


def add_nature_exclusive(apps, schema_editor):
    """Attach the new "document_nature" field to the manuscript document type."""
    DocumentType = apps.get_model("fiches", "DocumentType")
    for doctype in DocumentType.objects.filter(name=MANUSCRIPT_TYPE_NAME):
        fields = _exclusive_fields(doctype.exclusive_fields)
        if NATURE_FIELD not in fields:
            fields.append(NATURE_FIELD)
            doctype.exclusive_fields = ",".join(fields)
            doctype.save(update_fields=["exclusive_fields"])


def remove_nature_exclusive(apps, schema_editor):
    """Reverse: detach "document_nature" from the manuscript document type."""
    DocumentType = apps.get_model("fiches", "DocumentType")
    for doctype in DocumentType.objects.filter(name=MANUSCRIPT_TYPE_NAME):
        fields = [f for f in _exclusive_fields(doctype.exclusive_fields) if f != NATURE_FIELD]
        doctype.exclusive_fields = ",".join(fields)
        doctype.save(update_fields=["exclusive_fields"])


class Migration(migrations.Migration):
    dependencies = [
        ("fiches", "0018_place_verbose_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentNature",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128)),
                ("sorting", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Nature du document",
                "verbose_name_plural": "Natures de document",
                "ordering": ["sorting"],
            },
        ),
        migrations.AddField(
            model_name="biblio",
            name="document_nature",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="fiches.documentnature",
                verbose_name="Nature du document",
            ),
        ),
        migrations.RunPython(add_nature_exclusive, remove_nature_exclusive),
    ]
