# Generated by Django 5.2.14 on 2026-07-28 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fiches", "0019_document_nature"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="placerecord",
            options={
                "ordering": ("name",),
                "permissions": (
                    ("change_any_placerecord", "Can change any Lieu"),
                    ("delete_any_placerecord", "Can delete any Lieu"),
                ),
                "verbose_name": "Lieu",
                "verbose_name_plural": "Lieux",
            },
        ),
        migrations.AddField(
            model_name="placerecord",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_places",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Auteur de la fiche",
            ),
        ),
    ]
