# Generated by Django 5.2.14 on 2026-07-28 11:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fiches", "0020_alter_placerecord_options_placerecord_creator"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="placerecord",
            options={
                "ordering": ("name",),
                "permissions": (
                    ("change_any_placerecord", "Can change any Lieu"),
                    ("delete_any_placerecord", "Can delete any Lieu"),
                    ("add_placerecord_inline", "Can create a Lieu from the tagging toolbar"),
                ),
                "verbose_name": "Lieu",
                "verbose_name_plural": "Lieux",
            },
        ),
    ]
