# Generated by Django 5.2.14 on 2026-07-31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fiches", "0021_alter_placerecord_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={
                "app_label": "fiches",
                "ordering": ["name"],
                "permissions": (("add_person_inline", "Can create a Personne from the tagging toolbar"),),
                "verbose_name": "Personne",
                "verbose_name_plural": "Personnes",
            },
        ),
    ]
