# Generated by Django 5.2 on 2026-07-31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fiches", "0022_alter_person_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="documentfile",
            options={
                "permissions": (
                    ("change_any_documentfile", "Can change any Fichier"),
                    ("delete_any_documentfile", "Can delete any Fichier"),
                ),
                "verbose_name": "Fichier",
                "verbose_name_plural": "Fichiers",
            },
        ),
    ]
