# Generated by Django 5.2 on 2026-08-01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fiches", "0023_alter_documentfile_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="placecategory",
            options={
                "ordering": ("name",),
                "verbose_name": "Type de lieu",
                "verbose_name_plural": "Types de lieux",
            },
        ),
    ]
